name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dt-feature-github-ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Vuetify app
        run: npm run build

      - name: Deploy code to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}

        run: |
          echo "$EC2_USER"
          echo "$EC2_HOST"
          echo "$SSH_PRIVATE_KEY" > key.pem
        #   chmod 600 key.pem
        #   rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" dist/ $EC2_USER@$EC2_HOST:$TARGET_DIR

        #   rm key.pem
